# Generated by Django 2.2 on 2019-04-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0005_auto_20190424_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingsequa',
            name='message',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='outgoingseqworld',
            name='message',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_set', to='UPS.Warehouse'),
        ),
    ]
