# Generated by Django 2.2 on 2019-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.IntegerField(primary_key=True, serialize=False)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_set', to='UPS.Truck')),
            ],
        ),
    ]
