# Generated by Django 2.2 on 2019-04-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
