# Generated by Django 2.2 on 2019-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0002_truck_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingSeqUA',
            fields=[
                ('sequence_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingSeqWorld',
            fields=[
                ('sequence_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingSeqUA',
            fields=[
                ('sequence_number', models.IntegerField(primary_key=True, serialize=False)),
                ('acked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingSeqWorld',
            fields=[
                ('sequence_number', models.IntegerField(primary_key=True, serialize=False)),
                ('acked', models.BooleanField(default=False)),
            ],
        ),
    ]
