# Generated by Django 2.2 on 2019-04-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0004_auto_20190423_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
